from os import system
from time import sleep
time = .2

system('clear')
print('Loading… [][][][][][][][][][] 0%')
sleep(time)
system('clear')
print('Loading… ██[][][][][][][][][] 10%')
sleep(time)
system('clear')
print('Loading… ████[][][][][][][][] 20%')
sleep(time)
system('clear')
print('Loading… ██████[][][][][][][] 30%')
sleep(time)
system('clear')
print('Loading… ████████[][][][][][] 40%')
sleep(time)
system('clear')
print('Loading… ██████████[][][][][] 50%')
sleep(time)
system('clear')
print('Loading… ████████████[][][][] 60%')
sleep(time)
system('clear')
print('Loading… ██████████████[][][] 70%')
sleep(time)
system('clear')
print('Loading… ████████████████[][] 80%')
sleep(time)
system('clear')
print('Loading… ██████████████████[] 90%')
sleep(time)
system('clear')
print('Loading… ████████████████████ 100%')
